version: '3'

services:
  service:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5111:5000
    environment:
      #FLASK_DEBUG: 1
      FLASK_ENV: development
      #FLASK_APP: app.py
      WORK_ENV: DEV
    command: bash -c "python microservice.py"
    restart: unless-stopped
  service:
    build: ./frontend
    volumes:
    ports:
    environment:
    restart: unless-stopped
  database:
    build: ./database
    volumes:
    ports:
    environment:
    restart: unless-stopped