version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/usr/src/app
    ports:
      - 5000:5000
    environment:
      #FLASK_DEBUG: 1
      FLASK_ENV: development
      #FLASK_APP: app.py
      WORK_ENV: DEV
    command: bash -c "python app.py"
    restart: unless-stopped
    
  mongo:
    image: mongo
    volumes:
      - ./database/data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081