version: '3'

services:
  service:
    build: ./backend
    volumes:
      - ./backend/app:/usr/src/app
    ports:
      - 5000:5000
    environment:
      #FLASK_DEBUG: 1
      FLASK_ENV: development
      #FLASK_APP: app.py
      WORK_ENV: DEV
    command: bash -c "python app.py"
    restart: unless-stopped
  # service:
  #   build: ./frontend
  #   volumes:
  #   ports:
  #   environment:
  #   restart: unless-stopped
  # database:
  #   build: ./database
  #   volumes:
  #   ports:
  #   environment:
  #   restart: unless-stopped